CREATE TABLE IF NOT EXISTS note_pins (
    id       UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id  UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    note_id  UUID NOT NULL REFERENCES notes(id) ON DELETE CASCADE,
    pinned_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, note_id)
);

ALTER TABLE notes ADD COLUMN IF NOT EXISTS pinned_for_project BOOLEAN DEFAULT false;
ALTER TABLE notes ADD COLUMN IF NOT EXISTS pinned_by UUID REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE notes ADD COLUMN IF NOT EXISTS pinned_at TIMESTAMPTZ;
